packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@clerk/shared'
  - better-sqlite3
  - esbuild
  - sharp
  - workerd

patchedDependencies:
  '@expo/ui@57.0.22': patches/@expo__ui@57.0.22.patch
  wrangler@4.118.0: patches/wrangler@4.118.0.patch
