packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@clerk/shared'
  - esbuild
  - workerd

patchedDependencies:
  '@cloudflare/containers@0.3.7': patches/@cloudflare__containers@0.3.7.patch
  wrangler@4.103.0: patches/wrangler@4.103.0.patch


