/**
 * `Env` is generated by `wrangler types` from `wrangler.jsonc` plus the local
 * `.dev.vars` file (which `bin/fetch-secrets` syncs from Doppler). Re-export
 * the global so the rest of the code has a single import to lean on.
 */

export type Env = Cloudflare.Env;
